### ISSUE TITLE
Easily identify Chef employees

### ISSUE THREAD

**Issue by nathenharvey** [chef/mailing-list#7]
https://discourse.chef.io/t/chef-inc-members-identification/7107

**Comment by nathenharvey** [comment]
while Chef employees are "just" members of the community participating on the mailing list like everyone else I think it still makes sense to setup something like this. 

@coderanger created a new badge that auto-assigns based on a Chef email address.  I'm working with Andy on a custom image.

**Comment by coderanger** [comment]
Negatory on the custom badge image. It doesn't show up anywhere useful and would add to page load time for more or less no benefit.

**Comment by coderanger** [comment]
(right now it is using a Font Awesome glyph that is already loaded by the page, specifically a gold star)

**Comment by nathenharvey** [comment]
Yeah, Andy's looking at creating a Font Awesome glyph that we can use.

**Comment by coderanger** [comment]
To the best of my knowledge Font Awesome doesn't accept contributions and that would take 6+ months to be available even if they did, but okay. If you mean just picking a different fa icon class then sure, you can change it in the Badge admin UI.

**Comment by nathenharvey** [comment]
found this ... https://github.com/FortAwesome/Font-Awesome/issues/6110

**Comment by coderanger** [comment]
So functionally speaking I think this is as done as it can be, other than to remind staff to enable their title before posting (or someone can click through all ~100 of them and enable it for them).
