### ISSUE TITLE
Add "chef delivery" category

### ISSUE THREAD

**Issue by mgleasonchef** [chef/mailing-list#8]
We'd like to add a category for Delivery in discourse.  If possible, we may like to pin a message to the top of the category -- we can play around with that if needed.  Seth F and I should be admins for this category, if that is a thing.  Also would like integration into a Slack channel, let's call that delivery-discourse.  Please add as soon as possible.

**Comment by coderanger** [comment]
At this point this is :-/ due to how subscriptions were migrated. Any new topic would email every user by default, which is unlikely to be desired here. I've asked Nathen and the Discourse team to work towards fixing this so that we can add new categories without everyone being auto-subscribed to them.

**Comment by mgleasonchef** [comment]
Thanks Noah, that is legit and not delightful!  Working with Nathen on a plan.

**Comment by nathenharvey** [comment]
Here's what the impact would be:

Any subscriber who was migrated from the old system would automatically receive email notifications when topics are added in this new category.

One thing that might be feasible is to add the category and then immediately 'mute' the category for everyone in the system.  Anyone who wants email notifications for that category would need to explicitly opt-in.

That might be the easiest way forward for this particular topic.  What do you think?

**Comment by nathenharvey** [comment]
Another alternative is to direct members to use the 'chef' category for this particular topic and see if there is actually enough traffic to warrant creating a new category.

One way or another we need a forum for discussing specific products.  Barring a better user experience with categories and email subscriptions, we'll have to send people to one of the three existing categories 'chef', 'chef-dev', or 'Chef Forums Feedback'.

We have the same concerns with #2 which is another topic for security-announcements but that feels like less of an issue as it's likely that everyone subscribed to 'chef' would also want to hear about any security announcements.

I'm working with the Discourse team to explore options here.

**Comment by nathenharvey** [comment]
Current plan:

Add the category, immediately mute the category for all current members.

**Comment by coderanger** [comment]
Someone will need to add a section to the FAQ explaining this.

**Comment by nathenharvey** [comment]
This category has been created and added to the FAQ.

One outstanding question is the slug for the category once that's been resolved, I will close this ticket.

**Comment by nathenharvey** [comment]
Done

https://discourse.chef.io/c/delivery
